import { cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createRequire } from "node:module";
import { build } from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const { validateConfig } = require("../site/personal-library.js");
// Only these two explicitly public values ever enter the static output.
const envFile = path.join(root, ".env");
if (existsSync(envFile)) process.loadEnvFile(envFile);
const url = (process.env.SUPABASE_URL || "").trim();
const key = (process.env.SUPABASE_PUBLISHABLE_KEY || "").trim();
let config = null;
if (url || key) config = validateConfig({ url, publishableKey: key });
const local = path.join(root, ".local");
mkdirSync(local, { recursive: true });
if (realpathSync(local) !== path.join(realpathSync(root), ".local")) throw new Error("Refusing redirected build directory.");
const output = path.join(local, "site");
const stage = mkdtempSync(path.join(local, "site-build-"));
try {
  cpSync(path.join(root, "site"), stage, { recursive: true });
  writeFileSync(path.join(stage, "personal-config.js"),
    "window.RatesPersonalConfig = " + JSON.stringify(config) + ";\n");
  if (config) {
    const htmlPath = path.join(stage, "index.html");
    const html = readFileSync(htmlPath, "utf8");
    if (!html.includes("connect-src 'self';")) throw new Error("Unexpected CSP; refusing to widen it.");
    writeFileSync(htmlPath, html.replace("connect-src 'self';", "connect-src 'self' " + config.url + ";"));
  }
  await build({
    entryPoints: [path.join(root, "scripts", "supabase_entry.js")],
    outfile: path.join(stage, "vendor", "supabase.js"),
    bundle: true, minify: true, legalComments: "linked", platform: "browser", target: "es2022"
  });
  writeFileSync(path.join(stage, ".rates-site-build"), "Generated by scripts/build_site.mjs\n");
  if (existsSync(output)) {
    if (lstatSync(output).isSymbolicLink() || !existsSync(path.join(output, ".rates-site-build"))) {
      throw new Error("Refusing to replace an unrecognized build directory.");
    }
    // Exact generated output only, checked above; never remove the repository.
    rmSync(output, { recursive: true });
  }
  renameSync(stage, output);
} finally {
  if (existsSync(stage)) rmSync(stage, { recursive: true });
}
console.log("Static site ready in .local/site; personal sync " + (config ? "configured." : "disabled (public reading remains available)."));
